# Generated by Django 6.0.1 on 2026-01-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0005_alter_productrating_total_reviews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1 - Ruim'), (2, '2 - Médio'), (3, '3 - Bom'), (4, '4 - Muito bom'), (5, '5 - Excelente')]),
        ),
    ]
